---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${DOMAIN_NAME}
  namespace: default
spec:
  secretName: ${DOMAIN_NAME}-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "*.${DOMAIN}"
    - "${DOMAIN}"
